### ISSUE TITLE
RSS feeds aren't being displayed

### ISSUE THREAD

**Issue by odebroqueville** [avadhesh18/rssTea#2]
I've followed the 3 steps, but I'm not certain that I've done things correctly.

[This](https://odebroqueville.github.io/rssTea/) is what my web page looks like right now and it's not showing any feeds.

Here's what my settings look like:

<img width="802" alt="Screenshot 2023-12-29 at 20 04 31" src="https://github.com/avadhesh18/rssTea/assets/4818315/7ccca416-b5fe-43c6-8bd1-b155e4558b02">

UPDATE: I noticed that my Build and Deployment Source was incorrect, but I don't know what I'm to do next?!

<img width="802" alt="Screenshot 2023-12-29 at 20 26 31" src="https://github.com/avadhesh18/rssTea/assets/4818315/b3fae7f8-ed8e-41f1-8722-a6af7f5ab9d3">

**Comment by odebroqueville** [comment]
Finally got it working by running the workflow in Actions.

**Comment by fparri** [comment]
> Finally got it working by running the workflow in Actions.

I'm missing this last passage, can you please help me? :)

**Comment by odebroqueville** [comment]
Have you selected the “Build and deployment” source correctly:

￼

**Comment by odebroqueville** [comment]
Because you forked the rssTea repo, it contains the workflow YAML file main.yml:

￼

If I remember well, this is automagically picked up and you should find your workflow in the Actions tab. The only thing remaining to do is to Run the workflow:

￼
